repos:
  # Python formatting and linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff-format
        files: ^workflow/scripts/
      - id: ruff
        args: [--select=F, --ignore=F821, --fix]
        files: ^workflow/scripts/

  # Snakemake formatting
  - repo: https://github.com/snakemake/snakefmt
    rev: v0.11.0
    hooks:
      - id: snakefmt

  # Markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [markdown]
        args: [--prose-wrap, preserve]
