name: q100-smk
channels:
  - conda-forge
  - bioconda
channel_priority: strict
dependencies:
  - snakemake>=8.0
  - snakefmt
  - mamba
  - conda
  - graphviz
  - quarto
  - r-base
  - r-lintr
  - r-styler
  - markdownlint-cli
