name: Snakemake Workflow Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  r-format-suggest:
    name: R Format Suggest
    runs-on: ubuntu-latest

    permissions:
      # Required to push suggestion comments to the PR
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: R Air Install
        uses: posit-dev/setup-air@v1

      - name: R Air Format
        run: air format .

      - name: R AirSuggest
        uses: reviewdog/action-suggester@v1
        with:
          level: error
          fail_level: error
          tool_name: air

  py-format:
    name: Python Format
    runs-on: ubuntu-latest
    permissions:
      # Required to push suggestion comments to the PR
      pull-requests: write
    steps:
      - uses: astral-sh/ruff-action@v3

  smk-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Snakemake Linting
        uses: snakemake/snakemake-github-action@v2
        with:
          args: "--lint"

  smk-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run Snakemake Workflow
        uses: snakemake/snakemake-github-action@v2
        with:
          args: >-
            --conda-cleanup-pkgs cache
            --software-deployment-method conda
            --show-failed-logs
            --dry-run
